name: foodgram-workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r backend/requirements.txt
    - name: Test with flake8 python -m flake8
      run: |
        ls

  build_and_push_to_docker_hub:
      name: Push Docker images to Docker Hub
      if: github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - name: Check out the DH repo
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
 
        - name: Login to Docker 
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push backend's image to Docker Hub
          uses: docker/build-push-action@v2 
          with:
            push: true
            context: ./foodgram/backend/
            tags: natolin/foodgram:latest

        - name: Push frontend's image to Docker Hub
          uses: docker/build-push-action@v2 
          with:
            push: true
            context: ./foodgram/frontend/
            tags: natolin/foodgram_frontend:latest